### ISSUE TITLE
img.save(disp) can't save

### ISSUE THREAD

**Issue by NoiZeR355** [kscottz/dewarp#2]
Hello,

Im trying to test your code but when im running it with python dewrap.py. I gets the following error:

pi@raspberrypi ~/Downloads/dewarp-master $ python dewarp.py 
<SimpleCV.Image Object size:(0, 0), filename: (None), at memory location: (0x70e00be8)>
ERROR: 
Traceback (most recent call last):
  File "dewarp.py", line 48, in <module>
    img.show()
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV/ImageClass.py", line 5448, in show
    self.save(d)
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV/ImageClass.py", line 1984, in save
    saveimg = saveimg.toBGR()
  File "/usr/local/lib/python2.7/dist-packages/SimpleCV/ImageClass.py", line 1196, in toBGR
    cv.CvtColor(self.getBitmap(), retVal, cv.CV_RGB2BGR)
TypeError: CvArr argument 'src' must be IplImage, CvMat or CvMatND. Use fromarray() to convert numpy arrays to CvMat or cvMatND

Is it my issue or some mistake in the code?

**Comment by MattTucker22689** [comment]
Unfortunately the original code isn't my own. I ran into the same problem,
I just forked it on Git as a means of reference. I would suggest hitting up
a professor/teacher

**Comment by NoiZeR355** [comment]
Is there maybe a way to reach kscottz. Maybe she will know the answer.

**Comment by MattTucker22689** [comment]
I've tried once before and never got a response, but by all means....

**Comment by MattTucker22689** [comment]
- katherineascott@gmail.com
- http://www.kscottz.com

**Comment by NoiZeR355** [comment]
You need to install uv4l. That is a driver for the camera module. 
Here you can find the link where I found how to install it. 
http://www.linux-projects.org/modules/sections/index.php?op=viewarticle&artid=14
