### ISSUE TITLE
Type error: 'float' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by wrightwoldscientific** [kscottz/dewarp#5]
python2.7 dewarp.py
BUILDING MAP!
ERROR: 
Traceback (most recent call last):
  File "dewarp.py", line 78, in <module>
    xmap,ymap = buildMap(Ws,Hs,Wd,Hd,R1,R2,Cx,Cy)
  File "dewarp.py", line 20, in buildMap
    map_x = int(np.zeros((Hd,Wd),np.float32))
TypeError: 'float' object cannot be interpreted as an index

**Comment by yo-shari** [comment]
I have this issue too!!!
